modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="ward"
version="1.0.0"
displayName="forlorn"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Blue_Gamerwolf"
description="Tempararolry"

[[dependencies.ward]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.ward]]
    modId="bettercombat"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ward]]
    modId="create"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ward]]
    modId="playeranimator"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ward]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ward]]
    modId="cloth-config"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

